spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: snookerup
      username: appuser
      password: apppassword
      authentication-database: admin

logging:
  level:
    com:
      huwdunnit:
        snookeruprest: DEBUG
